version: "3.8"
services:
  spend-sentinel-telebot:
    build: .
    environment:
      - TRANSACTION_API_URL=http://transaction-api:8080/
    env_file:
      - ./secrets/botSecrets.env
    networks:
      - app-network

networks:
  app-network:
    external:
      name: spend-sentinel-app-network